### ISSUE TITLE
CRIAR PROCEDURE, quando digitar nota do aluno matriculado ja atribui status de aprovado ou nao

### ISSUE THREAD

**Issue by iksmada** [matheusvervloet/labbd2016#23]

**Comment by dcardos** [comment]
Vou criar uma trigger para isso, toda vez que alterar a nota já atribui conceito.

**Comment by dcardos** [comment]
Me equivoquei, a procedure que criei acho que nem estava aqui como issue! hahah

**Comment by bbortolli** [comment]
Trigger para essa função já está pronta e inserida no arquivo de triggers.
